version: '3'  # Укажите версию конфигурации Docker Compose
services:  # Определяем сервисы для приложения
  app:  # Имя сервиса (можно выбрать любое)
    build: .  # Строить образ из текущей директории (где находится Dockerfile)
    container_name: my_python_app  # Название контейнера (по желанию)
    command: python app.py  # Команда для запуска приложения внутри контейнера
    # Опционально: можно задать порты, переменные окружения и другие параметры.
    # ports:
    #   - "5000:5000"  # Пример привязки портов (если нужно)
    # environment:
    #   - MY_ENV_VAR=value  # Пример переменной окружения (если нужно)

   
